### ISSUE TITLE
`base.sprintf()` not working with Series as arguments

### ISSUE THREAD

**Issue by pwwang** [pwwang/datar#102]
```python
>>> from datar.base import sprintf
>>> from datar.tibble import tibble
>>> 
>>> df = tibble(x=[1, 2, 3])
>>> sprintf("%03d", 1)
array(['001'], dtype=object)
>>> sprintf("%03d", df.x)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    sprintf("%03d", df.x)
  File "/home/pwwang/github/pipda/pipda/register.py", line 484, in wrapper
    return calling_rule(generic, args, kwargs, envdata, verb_arg_only)
  File "/home/pwwang/github/pipda/pipda/_calling.py", line 186, in ndfunc_calling_rule2
    return generic(*args, **kwargs)
  File "/home/pwwang/github/datar/datar/core/factory.py", line 348, in _pipda_func
    out = dispatched(*bound.args, **bound.kwargs)
  File "/home/pwwang/miniconda3/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/pwwang/github/datar/datar/core/factory.py", line 174, in _dispatched
    return _apply_meta(
  File "/home/pwwang/github/datar/datar/core/factory.py", line 144, in _apply_meta
    raise ValueError(f"{exc} (registered function: {qualname})") from exc
ValueError: Transform function failed (registered function: sprintf)
```

R:
```R
r$> library(tibble)                                                                                   

r$> df = tibble(x=1:3)                                                                                

r$> sprintf("%03d", 1)                                                                                
[1] "001"

r$> sprintf("%03d", df$x)                                                                             
[1] "001" "002" "003"
```

**Comment by pwwang** [comment]
Fix at [0.7.2](https://github.com/pwwang/datar/releases/tag/0.7.2)
