### ISSUE TITLE
`Collection` object as indexers failed in pandas 1.3.0

### ISSUE THREAD

**Issue by pwwang** [pwwang/datar#23]
```python
>>> from datar.all import c
>>> from datar.datasets import mtcars
>>> 
>>> mtcars[c("cyl", "disp", "am", "drat")]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    mtcars[c("cyl", "disp", "am", "drat")]
  File "/.../python3.7/site-packages/pandas/core/frame.py", line 3445, in __getitem__
    if com.is_bool_indexer(key):
  File "/.../python3.7/site-packages/pandas/core/common.py", line 146, in is_bool_indexer
    return len(key) > 0 and lib.is_bool_list(key)
TypeError: Argument 'obj' has incorrect type (expected list, got Collection)
```

This works in pandas v1.2.*

This is a pandas bug in v1.3.0: https://github.com/pandas-dev/pandas/issues/42433

**Comment by pwwang** [comment]
Fixed at pandas 1.3.1
