### ISSUE TITLE
Piping syntax not running in raw python REPL

### ISSUE THREAD

**Issue by pwwang** [pwwang/datar#54]
@GitHunter0

I'm just having an issue with multi-line execution of `datar` code in VScode.

If a run this line by line, it works smoothly. 
```
from datar.all import (f, mutate, tibble, fct_infreq, fct_inorder, pull)
df = tibble(var=['b','b','b','c','a','a'])
df = df >> mutate(fct_var = f['var'].astype("category"))
```
However, if I select all the lines and execute them, it returns:
```
C:\Users\user_name\miniconda3\envs\py38\lib\site-packages\pipda\utils.py:161: UserWarning: Failed to fetch the node calling the function, call it with the original function.

>>> df = df >> mutate(fct_var = f['var'].astype("category"))

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user_name\miniconda3\envs\py38\lib\site-packages\pipda\register.py", line 396, in wrapper
    return calling_rule(generic, args, kwargs, envdata)
  File "C:\Users\user_name\miniconda3\envs\py38\lib\site-packages\pipda\_calling.py", line 93, in verb_calling_rule3
    return generic(*args, **kwargs)
  File "C:\Users\user_name\miniconda3\envs\py38\lib\functools.py", line 872, in wrapper
    raise TypeError(f'{funcname} requires at least '
TypeError: _not_implemented requires at least 1 positional argument
```

_Originally posted by @GitHunter0 in https://github.com/pwwang/datar/discussions/48#discussioncomment-1286583_

**Comment by pwwang** [comment]
@GitHunter0 

Looks like I can run the code you provided in a line-by-line manner or as a code block. See below:


https://user-images.githubusercontent.com/1188067/132262193-75297e53-95da-4c67-81f1-eeeb24a6df5a.mp4

**Comment by GitHunter0** [comment]
Hey @pwwang , it might be an issue with a specific VScode version, so I will do more tests and come back here with more details

**Comment by pwwang** [comment]
Thanks! BTW, I am using VSCode 1.60.0, Jupyter extension v2021.8.2031190714, python 3.9.5 and ipython 7.26.0

**Comment by GitHunter0** [comment]
Hey @pwwang , my VScode went nuts now, it is not even recognizing the right conda environment. I will fix it, make the tests and come back here soon

**Comment by GitHunter0** [comment]
After VScode updated with its new native notebook (my current version is 1.60.0), some issues occurred.

Therefore, I decided to test outside VScode, directly on Windows Terminal, and got the same issues.

I created a new conda environment with Python 3.9.5 and these are the results of the tests.

Running Line by Line:
```
>>> import datar

>>> from datar.all import *

>>> df = tibble(var=['b','b','b','c','a','a'])

>>> df = df >> mutate(fct_var = f['var'].astype("category"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\flavio\miniconda3\envs\datar2\lib\site-packages\pipda\register.py", line 396, in wrapper
    return calling_rule(generic, args, kwargs, envdata)
  File "C:\Users\flavio\miniconda3\envs\datar2\lib\site-packages\pipda\_calling.py", line 93, in verb_calling_rule3
    return generic(*args, **kwargs)
  File "C:\Users\flavio\miniconda3\envs\datar2\lib\functools.py", line 874, in wrapper
    raise TypeError(f'{funcname} requires at least '
TypeError: _not_implemented requires at least 1 positional argument

>>> df = mutate(df, fct_var = f['var'].astype("category"))
```
Apparently `>>`  is the problem.

Running All Lines at Once:
```
>>> import datar

>>> from datar.all import *

>>> df = tibble(var=['b','b','b','c','a','a'])
C:\Users\flavio\miniconda3\envs\datar2\lib\site-packages\pipda\utils.py:161: UserWarning: Failed to fetch the node calling the function, call it with the original function.
  warnings.warn(

>>> df = df >> mutate(fct_var = f['var'].astype("category"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\flavio\miniconda3\envs\datar2\lib\site-packages\pipda\register.py", line 396, in wrapper
    return calling_rule(generic, args, kwargs, envdata)
  File "C:\Users\flavio\miniconda3\envs\datar2\lib\site-packages\pipda\_calling.py", line 93, in verb_calling_rule3
    return generic(*args, **kwargs)
  File "C:\Users\flavio\miniconda3\envs\datar2\lib\functools.py", line 874, in wrapper
    raise TypeError(f'{funcname} requires at least '
TypeError: _not_implemented requires at least 1 positional argument

>>> df = mutate(df, fct_var = f['var'].astype("category"))
```
We can see that there is one additional message: `UserWarning: Failed to fetch the node calling the function, ...`

@pwwang , on what OS have you tested? Maybe it is a Windows issue.

```
Windows 10 Pro 64 Bits
Miniconda 3

asttokens                 2.0.5                    pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
datar                     0.5.0                    pypi_0    pypi
debugpy                   1.4.1            py39h415ef7b_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
diot                      0.1.1                    pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
executing                 0.8.0                    pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
ipykernel                 6.4.1            py39h832f523_0    conda-forge
ipython                   7.27.0           py39h832f523_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py39hcbf5309_2    conda-forge
jupyter_client            7.0.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hcbf5309_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
numpy                     1.21.2                   pypi_0    pypi
openssl                   1.1.1l               h8ffe710_0    conda-forge
pandas                    1.3.2                    pypi_0    pypi
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pipda                     0.4.5                    pypi_0    pypi
prompt-toolkit            3.0.20             pyha770c72_0    conda-forge
pure-eval                 0.2.1                    pypi_0    pypi
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
python                    3.9.5           h7840368_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1                   pypi_0    pypi
pywin32                   301              py39hb82d6ee_0    conda-forge
pyzmq                     22.2.1           py39he46f08e_0    conda-forge
scipy                     1.7.1                    pypi_0    pypi
setuptools                58.0.4           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h8ffe710_1    conda-forge
text-unidecode            1.3                      pypi_0    pypi
tornado                   6.1              py39hb82d6ee_1    conda-forge
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
varname                   0.8.1                    pypi_0    pypi
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
```

**Comment by pwwang** [comment]
@GitHunter0 Are you running it in raw `python` REPL directly instead of `ipython`?

Like:
```python
(base) C:\Users\pwwan>python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from datar.all import *
[2021-09-12 09:54:45][datar][WARNING] Builtin name "min" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "max" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "sum" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "abs" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "round" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "all" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "any" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "re" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "filter" has been overriden by datar.
[2021-09-12 09:54:45][datar][WARNING] Builtin name "slice" has been overriden by datar.
>>> df = tibble(var=['b','b','b','c','a','a'])
D:\miniconda3\lib\site-packages\pipda\utils.py:161: UserWarning: Failed to fetch the node calling the function, call it with the original function.
  warnings.warn(
>>> 
```

Instead of :
```python
(base) C:\Users\pwwan>ipython
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from datar.all import *
[2021-09-12 09:56:04][datar][WARNING] Builtin name "min" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "max" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "sum" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "abs" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "round" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "all" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "any" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "re" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "filter" has been overriden by datar.
[2021-09-12 09:56:04][datar][WARNING] Builtin name "slice" has been overriden by datar.

In [2]: df = tibble(var=['b','b','b','c','a','a'])

In [3]: df
Out[3]: 
       var
  <object>
0        b
1        b
2        b
3        c
4        a
5        a
```

If that's the case, then https://github.com/pwwang/datar/issues/45 is related.

**Comment by GitHunter0** [comment]
You're right @pwwang , using ipython solved the issue in Terminal (and probably my VScode was having problems with ipython, which then caused the same issue. When I reinstall it, I will try again).

Thank you, feel free to close the issue.

**Comment by pwwang** [comment]
You are welcome! Feel free to reopen it or open new ones if you have other issues.

I should probably have a session in the doc to mention the raw python REPL.

Thanks for reporting.
