### ISSUE TITLE
Cannot import datar on VScode

### ISSUE THREAD

**Issue by GitHunter0** [pwwang/datar#57]
Hey @pwwang , I reinstalled VScode and a new strange issue appeared.

In the Interactive Window, `import pandas` for example is running smoothly, however `import datar` throws this error: 
```
SyntaxError: unexpected EOF while parsing (datar.py, line 17)
Traceback (most recent call last):

  File "C:\Users\flavio\miniconda3\envs\py38\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "C:\Users\flavio\AppData\Local\Temp/ipykernel_8104/1528111572.py", line 1, in <module>
    import datar

  File "d:\temp_download\datar.py", line 17
    
    ^
SyntaxError: unexpected EOF while parsing
```
The same error also appears when running the line from a .py file. Nonetheless, running directly in Terminal works as expected.

```
VScode 1.60.1
Windows 10 Pro 64 bits
Miniconda 3

asttokens                 2.0.5                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bottleneck                1.3.2            py38h2a96729_1
ca-certificates           2021.7.5             haa95532_1
certifi                   2021.5.30        py38haa95532_0
colorama                  0.4.4              pyhd3eb1b0_0
datar                     0.5.0                    pypi_0    pypi
debugpy                   1.4.1            py38hd77b12b_0
decorator                 5.0.9              pyhd3eb1b0_0
diot                      0.1.1                    pypi_0    pypi
entrypoints               0.3                      py38_0
executing                 0.8.1                    pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
intel-openmp              2021.3.0          haa95532_3372
ipykernel                 6.2.0            py38haa95532_1
ipython                   7.26.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.18.0           py38haa95532_1
jupyter_client            7.0.1              pyhd3eb1b0_0
jupyter_core              4.7.1            py38haa95532_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mkl                       2021.3.0           haa95532_524
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.0            py38h277e83a_2
mkl_random                1.2.2            py38hf11a4ad_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
numexpr                   2.7.3            py38hb80d3ca_1
numpy                     1.20.3           py38ha4e8547_0
numpy-base                1.20.3           py38hc2deb75_0
openssl                   1.1.1l               h2bbff1b_0
pandas                    1.3.2            py38h6214cd6_0
parso                     0.8.2              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       21.2.2           py38haa95532_0
pipda                     0.4.5                    pypi_0    pypi
plotly                    5.3.1                    pypi_0    pypi
prompt-toolkit            3.0.17             pyhca03da5_0
pure-eval                 0.2.1                    pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0
python                    3.8.10               hdbf39b2_7
python-dateutil           2.8.2              pyhd3eb1b0_0
python-slugify            5.0.2                    pypi_0    pypi
pytz                      2021.1             pyhd3eb1b0_0
pywin32                   228              py38hbaba5e8_1
pyzmq                     22.2.1           py38hd77b12b_1
scipy                     1.7.1                    pypi_0    pypi
setuptools                52.0.0           py38haa95532_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               h2bbff1b_0
tenacity                  8.0.1                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
tornado                   6.1              py38h2bbff1b_0
traitlets                 5.0.5              pyhd3eb1b0_0
varname                   0.8.1                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
wheel                     0.37.0             pyhd3eb1b0_1
wincertstore              0.2                      py38_0
```

**Comment by rleyvasal** [comment]
@GitHunter0 

I am not sure this is a problem with `datar`. 

I have the same version of  `datar` and `varname` as you, with latest version of VScode (Anaconda 3), and I do not get any error message: look at screenshots below

<img width="976" alt="import_datar" src="https://user-images.githubusercontent.com/61335136/133496995-5fa628e3-eaa2-4995-8f82-388b31de715d.PNG">

<img width="993" alt="import_datar_notebook" src="https://user-images.githubusercontent.com/61335136/133497449-237da27e-0135-4ade-88d4-05bd9f6fddb1.PNG">

**Comment by pwwang** [comment]
@GitHunter0 
It is apparently wired that you have "d:\temp_download\datar.py" in the stack trace. `datar` itself doesn't have this file, the entrance should be in somewhere like `.../site-packages/.../datar/__init__.py`.

Have you installed `datar` via `pip`? If so, you must have your `$PYTHONPATH` polluted.

**Comment by GitHunter0** [comment]
Yes @pwwang , I installed via pip as I normally.
I managed to solve the issue by starting a new VScode project and open the file `datar.py` from there.
Thank you folks
